url: codejamteam2.github.io
baseurl: /

# Site settings
title: Mental Health
description: "How to apporach Mental Health."

# Team names, titles and social links
people:
- name: Agni
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Bryce
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Arya
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/webcc_
  - title: github
    url: http://github.com/davetss

# Postal address (add as many lines as necessary)
address:
  - line: Cerritos, CA

# Build settings
markdown: kramdown
permalink: pretty
